import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's github repository
*/
`;

const production = process.argv[2] === "production";

/** Modules that only exist inside the Obsidian/Electron runtime. */
const obsidianExternals = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtins,
];

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["main.ts"],
	bundle: true,
	external: obsidianExternals,
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: production ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	define: {
		"process.env.NODE_ENV": production ? '"production"' : '"development"',
	},
});

if (production) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
